[build.environment]
  NODE_VERSION = "8.12.0"
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--frozen-lockfile"
  BABEL_CACHE_FOLDER = "/opt/build/cache/"
  BUILD_REPORT_ERRORS_ONLY = "true"

[[headers]]
for = "/*.otf"
	[headers.values]
	Access-Control-Allow-Origin = "*"
	Content-Type = "application/font-otf"

[[headers]]
for = "/*.ttf"
	[headers.values]
	Access-Control-Allow-Origin = "*"
	Content-Type = "application/font-ttf"

[[headers]]
    for = "/*.json"
    	[headers.values]
    	Access-Control-Allow-Origin = "*"
    	Content-Type = "application/json"

[[headers]]
for = "/*.ttc"
	[headers.values]
	Access-Control-Allow-Origin = "*"
	Content-Type = "application/font-ttc"

[[headers]]
for = "/*.woff2"
	[headers.values]
	Access-Control-Allow-Origin = "*"
	Content-Type = "application/font-woff2"

[[headers]]
for = "/*.woff"
	[headers.values]
	Access-Control-Allow-Origin = "*"
	Content-Type = "application/font-woff"

[[headers]]
for = "/*.eot"
	[headers.values]
	Access-Control-Allow-Origin = "*"
	Content-Type = "application/font-eot"
